# Generated by Django 6.0.7 on 2026-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
