# Generated by Django 6.0.7 on 2026-07-28 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0002_alter_trade_exit_price_alter_trade_profit_loss_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('BUY', 'Buy / Long'), ('SELL', 'Sell / Short')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('exit_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('strategy_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('risk_reward_ratio', models.FloatField(blank=True, null=True)),
                ('ai_feedback_summary', models.TextField(blank=True, null=True)),
                ('discipline_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeChartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_charts/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_images', to='tradelog.tradejournal')),
            ],
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
