# Generated by Django 6.0.7 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0003_tradejournal_tradechartimage_delete_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('Banking', 'Banking'), ('Telecommunication', 'Telecommunication & Tech'), ('Energy', 'Energy & Petroleum'), ('Manufacturing', 'Manufacturing & Allied'), ('Insurance', 'Insurance'), ('Commercial', 'Commercial & Services')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_pct', models.FloatField(help_text='24-hour percentage change')),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('div_yield', models.FloatField(default=0.0, help_text='Dividend yield percentage')),
                ('volume', models.CharField(help_text='e.g. 4.2M', max_length=20)),
                ('market_cap', models.CharField(help_text='e.g. 729.1B', max_length=20)),
                ('signal', models.CharField(choices=[('BULLISH', 'BUY'), ('BEARISH', 'SELL'), ('NEUTRAL', 'HOLD')], default='NEUTRAL', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
