# Generated by Django 6.0.7 on 2026-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='e.g. BTCUSDT', max_length=20, unique=True)),
                ('base_asset', models.CharField(help_text='e.g. BTC', max_length=10)),
                ('quote_asset', models.CharField(default='USDT', help_text='e.g. USDT', max_length=10)),
                ('category', models.CharField(choices=[('Linear Perpetual', 'USDT Perpetual'), ('USDC Perpetual', 'USDC Perpetual'), ('Inverse Perpetual', 'Inverse Perpetual'), ('Spot', 'Spot Trading')], default='Linear Perpetual', max_length=30)),
                ('mark_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('change_pct', models.FloatField(help_text='24-hour percentage change')),
                ('funding_rate', models.FloatField(default=0.0, help_text='8-hour funding rate percentage (e.g. 0.0100)')),
                ('open_interest', models.CharField(help_text='e.g. 12.4K BTC', max_length=30)),
                ('turnover', models.CharField(help_text='24h volume/turnover formatted e.g. 4.5B', max_length=30)),
                ('turnover_m', models.FloatField(default=0.0, help_text='Raw 24h turnover in Millions USD for filtering')),
                ('signal', models.CharField(choices=[('BULLISH', 'BUY'), ('BEARISH', 'SELL'), ('NEUTRAL', 'HOLD')], default='NEUTRAL', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Asset',
                'verbose_name_plural': 'Crypto Assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
