# Generated by Django 6.0.7 on 2026-08-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradelog', '0005_crypto_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('order_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Filled', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
